@extends('layouts.app')

@section('content')
<div class="breadcrumb-area" style="background-image: url('public/assets/img/breadcrumb/02.png')">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-inner text-center">
                    <h1 class="page-title">Términos y Condiciones</h1>
                    <ul class="page-list">
                        <li><a href="/">Home</a></li>
                        <li>Términos y Condiciones</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!--// Breadcrumb End-->

<div class="accordion padding-top-30 padding-bottom-160">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 padding-top-70">
                <div class="accordion-wrapper">
                    <div id="accordionOne">
                        <div class="card">
                            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionOne">
                                <div class="card-body">
                                    <p align="left"><strong>Asesorautos.com.ar</strong> es un sitio de Internet que presta un servicio de b&uacute;squeda de autom&oacute;viles para la compra y venta de terceros y servicios relacionados. Toda persona que haga uso de los servicios de <strong>Asesorautos.com.ar</strong> estar&aacute; obligada a aceptar y cumplir los presentes t&eacute;rminos y condiciones de uso, en adelante los &ldquo;T&eacute;rminos y Condiciones&rdquo; bajo su responsabilidad. Toda referencia en los presentes T&eacute;rminos y Condiciones a <strong>Asesorautos.com.ar </strong>debe entenderse &ndash;en cuanto resulte aplicable- que abarca tambi&eacute;n a las personas f&iacute;sicas que por cualquier vinculaci&oacute;n jur&iacute;dica sean representantes y/o responsables y/o controlantes, de <strong>Asesorautos.com.ar.</strong></p>
                                    <br>
                                    <p align="left">
                                        <strong>Asesorautos.com.ar</strong> se reserva el derecho, a su arbitrio, de modificar, los T&eacute;rminos y Condiciones en cualquier momento, sin obligaci&oacute;n de informar los cambios efectuados a los usuarios, motivo por el cual le sugerimos que los verifique peri&oacute;dicamente. Todas las modificaciones tendr&aacute;n vigencia inmediata. Toda persona que haga uso de los servicios estar&aacute; obligada por los T&eacute;rminos y Condiciones al momento de utilizarlos.<br />
                                        Los contenidos de los presentes T&eacute;rminos y Condiciones pueden estar alcanzados por normas especificas que reglamenten y complementen a los presentes, raz&oacute;n por la cual, le sugerimos tomar conocimiento de ellas. </p>
                                        <br>
                                        <p align="left">
                                        <strong>(I) Utilizaci&oacute;n del Servicio:</strong><br />
                                        Al utilizar nuestros servicios, Usted <strong>(i)</strong> declara y reconoce que ha le&iacute;do y comprendido en su totalidad los T&eacute;rminos y Condiciones aqu&iacute; descriptos , y <strong>(ii)</strong> acepta los presentes T&eacute;rminos y Condiciones en su totalidad, salvo modificaci&oacute;n efectuada por escrito y acordada de mutuo acuerdo por las partes. Queda prohibida la utilizaci&oacute;n de nuestros servicios y/o la contrataci&oacute;n de los mismos por personas que carezcan de capacidad legal para contratar los productos y/o servicios ofrecidos en el mismo. <br />
                                        Asimismo, queda tambi&eacute;n prohibido, a t&iacute;tulo enunciativo y en ning&uacute;n caso limitativo o excluyente realizar alguno o algunos de los actos que se listan a continuaci&oacute;n al navegar por <strong>Asesorautos.com.ar</strong>: <strong>(i)</strong>enviar o trasmitir actividades il&iacute;citas o constitutivas de delito, contrarias a la buena fe, la moral y el orden p&uacute;blico, a los usos, y/o que infrinja la regulaci&oacute;n sobre propiedad intelectual e industrial, o cualesquiera otra norma del Ordenamiento Jur&iacute;dico aplicable, (ii) enviar o transmitir material racista, de apolog&iacute;a terrorista o contrarios a los derechos humanos, sexual u obsceno; <strong>(iii)</strong> enviar o transmitir informaci&oacute;n cuyo contenido sea, directa o indirectamente, y sin que lo siguiente se considere una limitaci&oacute;n, transgresor, profano, abusivo, difamatorio y/o fraudulento; <strong>(iv)</strong> enviar o transmitir archivos que contengan virus u otras caracter&iacute;sticas destructivas que puedan afectar de manera adversa el funcionamiento de una computadora ajena y/o puedan afectar el correcto funcionamiento de las mismas y/o del sitio; <strong>(v) </strong>utilizar <strong>Asesorautos.com.ar</strong>, directa o indirectamente, para violar cualquier ley aplicable, cualquiera fuese su naturaleza, ya sea provincial, nacional o internacional; <strong>(vi)</strong> utilizar nuestro servicios utilizando un nombre falso, err&oacute;neo y/o inexistente, ya sea como persona f&iacute;sica o jur&iacute;dica; <strong>(vii)</strong> enviar y/o transmitir informaci&oacute;n de terceros&nbsp; que pudiera afectar adversamente la imagen y/o los derechos de terceros; <strong>(viii)</strong> ofrecer productos o servicios, sean propios y/o de terceros; y (ix) realizar cualquier acto contrario a, o que de cualquier manera viole los presentes T&eacute;rminos y Condiciones. <strong>Asesorautos.com.ar</strong> &nbsp;se reserva el derecho, en cualquier momento y sin necesidad de darle notificaci&oacute;n previa al usuario del servicio, de retirar y/o modificar y/o actualizar cualquier publicaci&oacute;n.</p>
                                        <br>
                                        <p align="left">
                                        <strong>(II) Servicios de Asesorautos.com.ar:</strong><br />
                                        <strong>Asesorautos.com.ar</strong> no pretende ser una lista exhaustiva de todos los productos del mercado.<br />
                                        <strong>Asesorautos.com.ar </strong>&nbsp;no garantiza la exactitud y/o veracidad de la informaci&oacute;n contenida en <strong>Asesorautos.com.ar</strong> que puede contener datos inexactos, incorrectos y/o errores sustanciales o tipogr&aacute;ficos. <br />
                                        <strong>Asesorautos.com.ar</strong> no asume ninguna responsabilidad respecto de la veracidad ni exactitud de los datos consignados. La informaci&oacute;n brindada respecto de los productos y servicios deber&aacute; pues, ser objeto de una investigaci&oacute;n independiente y propia del usuario no asumiendo <strong>Asesorautos.com.ar</strong> ning&uacute;n tipo de responsabilidad por informaci&oacute;n incorrecta, desactualizada o que de alguna forma no sea veraz. Por lo tanto ning&uacute;n da&ntilde;o o perjuicio ocasionado a los usuarios, clientes, visitantes del servicio de <strong>Asesorautos.com.ar</strong> y/o terceros por la informaci&oacute;n que proporciona ser&aacute;n responsabilidad de <strong>Asesorautos.com.ar</strong>. <br />
                                        <strong>Asesorautos.com.ar</strong> no garantiza la exactitud y/o la veracidad de la informaci&oacute;n provista por los oferentes y contenida en <strong>Asesorautos.com.ar</strong>, ni de los cambios sobre la misma que pudieran acontecer, ni asegura el cumplimiento por parte de los mismos de la calidad o exactitud de los productos y/o servicios ofrecidos, ni asegura el cumplimiento de la normativa vigente aplicable a la comercializaci&oacute;n de dichos productos y/o servicios. <strong>Asesorautos.com.ar</strong> no asume obligaci&oacute;n alguna respecto del usuario y se limita a publicar en forma similar a aquella en que lo har&iacute;a una gu&iacute;a telef&oacute;nica o la secci&oacute;n clasificados de un peri&oacute;dico, los datos de los proveedores de productos o servicios que han solicitado tal publicaci&oacute;n y en la forma en que tales datos han sido proporcionados por tales proveedores. <strong>Asesorautos.com.ar</strong>, pues, no pretende ser, ni <strong>Asesorautos.com.ar</strong> pretende brindar, una lista exhaustiva de los proveedores y <strong>Asesorautos.com.ar</strong> no garantiza en forma alguna que no haya otros proveedores de tales productos ni que no existan en el mercado ofertas m&aacute;s convenientes, en precio o condiciones, de tales productos, ni que no existan otros productos que cumplan la misma funci&oacute;n. Tampoco <strong>Asesorautos.com.ar</strong> responde por la veracidad ni exactitud de los datos consignados, los cuales han sido volcados, o son proporcionados a los usuarios en la misma forma en que son proporcionados por los proveedores a <strong>Asesorautos.com.ar</strong>, sin ninguna verificaci&oacute;n de ning&uacute;n tipo.<br />
                                        <strong>Asesorautos.com.ar</strong> no se responsabiliza por la veracidad de los datos, informaciones, fotograf&iacute;as, descripciones y caracter&iacute;sticas de los autom&oacute;viles publicados, siendo los mismos informados por los propietarios de los mismos. . <br />
                                        <strong>Asesorautos.com.ar</strong> no se responsabiliza por el estado de la documentaci&oacute;n de los autom&oacute;viles publicados, como as&iacute; tampoco por la disponibilidad para la venta de los mismos. <strong>Asesorautos.com.ar</strong> no se responsabiliza por el estado mec&aacute;nico y/o t&eacute;cnico de los productos y/o servicios ofrecidos, ni por los vicios ocultos o redhibitorios de los autom&oacute;viles.<br />
                                        <strong>Asesorautos.com.ar</strong> no se responsabiliza por los resultados de las operaciones que resulten.<br />
                                        <strong>Asesorautos.com.ar</strong> no otorga garant&iacute;a de evicci&oacute;n ni por vicios ocultos o aparentes de los bienes ofrecidos por los vendedores y adquiridos por los usuarios. <strong>Asesorautos.com.ar</strong> no es propietario de los bienes y servicios que se publicitan, ni garantiza en forma alguna dichos bienes y servicios (tanto respecto de su calidad o entrega como respecto de ning&uacute;n otro aspecto), ni garantiza a los usuarios, clientes, visitantes de <strong>Asesorautos.com.ar</strong> y/o terceros respecto de la existencia, cr&eacute;dito, capacidad ni sobre ning&uacute;n otro aspecto de los proveedores de tales bienes y servicios. Los usuarios, clientes, visitantes de <strong>Asesorautos.com.ar</strong> y/o terceros deber&aacute;n, en consecuencia, hacer su propia e independiente investigaci&oacute;n al respecto no asumiendo <strong>Asesorautos.com.ar</strong> ning&uacute;n tipo de responsabilidad por informaci&oacute;n incorrecta, desactualizada o que de alguna forma no sea veraz.<br />
                                        Por lo tanto ning&uacute;n da&ntilde;o o perjuicio ocasionado a los usuarios, clientes, visitantes de <strong>Asesorautos.com.ar</strong> y/o terceros ser&aacute;n de responsabilidad de <strong>Asesorautos.com.ar</strong>. <strong>Asesorautos.com.ar</strong> no asume obligaci&oacute;n alguna con el usuario. <strong>Asesorautos.com.ar</strong> no asume responsabilidad alguna respecto de la capacidad invocada por los vendedores para vender y los compradores para comprar los productos y/o servicios brindados en <strong>Asesorautos.com.ar</strong>. <strong>Asesorautos.com.ar</strong> no asume responsabilidad alguna por el incumplimiento de los t&eacute;rminos y condiciones pactados por los vendedores y los compradores de los productos y/o servicios ofrecidos.<br />
                                        Usted declara conocer y aceptar que <strong>Asesorautos.com.ar</strong> no tiene control -sin que lo siguiente se considere una limitaci&oacute;n- sobre la calidad, seguridad, contenido, especificaciones t&eacute;cnicas y/o legalidad y/o sobre la veracidad y exactitud de las descripciones efectuadas de los productos y/o servicios ofrecidos en <strong>Asesorautos.com.ar.</strong> Toda la informaci&oacute;n contenida en el sitio ha sido y ser&aacute; provista por terceras personas ajenas a la misma. Usted mantendr&aacute; indemne a <strong>Asesorautos.com.ar</strong> y sus titulares, representantes, y/o controlantes, de y contra todo da&ntilde;o y/o perjuicio, cualquiera fuese su naturaleza, derivado u ocasionado, directa o indirectamente, por la utilizaci&oacute;n de los servicios y/o por la compra de los productos ofrecidos en <strong>Asesorautos.com.ar. </strong>Todo reclamo, cualquiera fuese su naturaleza, deber&aacute; dirigirse exclusivamente a los fabricantes y/o propietarios de los productos y/o servicios ofrecidos. <br />
                                        Usted acepta y reconoce que el sistema puede no siempre estar disponible debido a dificultades t&eacute;cnicas o fallas de Internet, o por cualquier otro motivo ajeno a <strong>Asesorautos.com.ar</strong>, motivo por el cual no podr&aacute; imput&aacute;rsele responsabilidad alguna. <strong>Asesorautos.com.ar</strong> no ser&aacute; responsable por los servicios prestados, cuando los mismos tengan fallas, debido a cortes de energ&iacute;a o interrupciones o cualquier otra falla ocasionada por situaciones no atribuibles a Asesorautos. El contenido de la pantalla relativa a <strong>Asesorautos.com.ar</strong>, junto con -y sin que la enumeraci&oacute;n sguiente se considere una limitaci&oacute;n-, sus programas, bases de datos, redes y archivos son de propiedad de <strong>Asesorautos.com.ar</strong>. Su uso indebido as&iacute; como su reproducci&oacute;n ser&aacute;n objeto de las acciones judiciales que correspondan. El presente no podr&aacute; ser interpretado como un contrato de sociedad, mandato o que genere ning&uacute;n tipo de relaci&oacute;n entre <strong>Asesorautos.com.ar</strong> y Usted. La utilizaci&oacute;n de los servicios brindados por <strong>Asesorautos.com.ar</strong> no podr&aacute;, en ning&uacute;n supuesto, ser interpretada como una autorizaci&oacute;n y/o concesi&oacute;n de licencia de los derechos intelectuales de <strong>Asesorautos.com.ar</strong> y/o de un tercero.<br />
                                        <strong>Asesorautos.com.ar</strong> no ser&aacute; responsable por los da&ntilde;os y perjuicios que se ocasionen por alteraci&oacute;n de la informaci&oacute;n al sistema o a las redes producto del accionar de terceros.<br />
                                        La falta de ejercicio por parte de <strong>Asesorautos.com.ar</strong> de los derechos que los presentes T&eacute;rminos y Condiciones le confieren, no implicar&aacute; renuncia a los mismos, los cuales podr&aacute;n ser ejercidos por <strong>Asesorautos.com.ar</strong> en otra ocasi&oacute;n.</p>
                                        <br>
                                        <p align="left">
                                        <strong>(III) Privacidad:</strong><br />
                                        Usted acepta, por el hecho de operar con <strong>Asesorautos.com.ar</strong>, el derecho de <strong>Asesorautos.com.ar</strong> de comunicarse con Usted por v&iacute;a electr&oacute;nica o telef&oacute;nica hasta que Usted manifieste fehacientemente que no desea ser contactado por <strong>Asesorautos.com.ar</strong>. <strong>Asesorautos.com.ar</strong> tendr&aacute; derecho de ofrecerle mediante correo electr&oacute;nico y/o tel&eacute;fono y/o mensaje de texto, servicios o productos relacionados con la compraventa de autos, incluyendo pero no limit&aacute;ndose a la oferta de seguros, ya sea por s&iacute; o asociada con otras empresas.</p>
                                        <br>
                                        <p align="left">
                                        <strong>(IV) Legislaci&oacute;n aplicable:</strong><br />
                                        Los presentes T&eacute;rminos y Condiciones se regir&aacute;n e interpretaran de conformidad con las Leyes de la Rep&uacute;blica Argentina.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection